### ISSUE TITLE
Feedback DateTimePicker BUG

### ISSUE THREAD

**Issue by tcqq** [Gericop/DateTimePicker#4]
Click redbox button before:
![image](https://user-images.githubusercontent.com/10644057/35187495-875311fe-fe5f-11e7-8a74-7497e6975dca.png)
Click redbox button after:
![image](https://user-images.githubusercontent.com/10644057/35187499-a97ccc2a-fe5f-11e7-957e-1c3cc6d39448.png)

**Comment by gregkorossy** [comment]
What's the exact question / issue?

**Comment by tcqq** [comment]
Header layout height be changed.
![image](https://user-images.githubusercontent.com/10644057/35187828-7e3c7866-fe65-11e7-8e74-3228250e1fbc.png)
![image](https://user-images.githubusercontent.com/10644057/35187829-815dae84-fe65-11e7-89b6-fed28fb7b05e.png)

**Comment by gregkorossy** [comment]
Looks good on my device. What Android version and what device is that?

**Comment by tcqq** [comment]
Pixel xl

**Comment by gregkorossy** [comment]
Is this happening with the current released version of the lib or just the one you modified?

**Comment by tcqq** [comment]
Now I just added more than one setColor method, I did not change the original function of this library

**Comment by tcqq** [comment]
android studio have this simulators
![image](https://user-images.githubusercontent.com/10644057/35187931-dc1eff9c-fe67-11e7-89b1-8d1761d2d16e.png)

**Comment by tcqq** [comment]
I tested, this problem is real.
![image](https://user-images.githubusercontent.com/10644057/35187939-1a9189ca-fe68-11e7-8968-a624f51e1646.png)
![image](https://user-images.githubusercontent.com/10644057/35187941-26e30352-fe68-11e7-9158-1c6e6c735f9d.png)

**Comment by gregkorossy** [comment]
I understand that, but still, could you try if this is happening with the released one too? My device (HTC 10, 8.0) does not produce this, so it could be either a modification you made or the locale (yours is Chinese if I'm right, mine is English).

**Comment by tcqq** [comment]
Yes, I will try, when the problem is solved I will let you know.

**Comment by tcqq** [comment]
I fixed this problem, but i find a new problem
[image.zip](https://github.com/Gericop/DateTimePicker/files/1649298/image.zip)

![image](https://user-images.githubusercontent.com/10644057/35188315-fbb1c834-fe6d-11e7-843c-c22871f13068.png)
![image](https://user-images.githubusercontent.com/10644057/35188316-027d06ce-fe6e-11e7-9231-d170d505bd0f.png)

**Comment by tcqq** [comment]
After the horizontal screen there will be problems, This is before the above code is run the screenshot.
![image](https://user-images.githubusercontent.com/10644057/35188347-9974a3a2-fe6e-11e7-91c3-eee8a937224c.png)

**Comment by tcqq** [comment]
I fixed this problem, The problem is because of the "setHeaderBackgroundColor" method.

If I use "setBackgroundColor" to set it will not have problem, if I use "setBackground" to set, it will have problem.
![image](https://user-images.githubusercontent.com/10644057/35192543-8e688c38-fecf-11e7-94e4-1aca4047907f.png)
![image](https://user-images.githubusercontent.com/10644057/35192577-61102628-fed0-11e7-8bb3-e0a278bad95b.png)

![image](https://user-images.githubusercontent.com/10644057/35192544-92335d0c-fecf-11e7-853f-9cfa8f03b5d8.png)
![image](https://user-images.githubusercontent.com/10644057/35192572-48f9aae6-fed0-11e7-9891-f4e0a85e5dd9.png)


But the strange thing is that the above initialization is using "setBackground" but no problem.
![image](https://user-images.githubusercontent.com/10644057/35192557-c0620fe8-fecf-11e7-8963-e146cf10d4b8.png)

I really want to know why this is, if you know, please tell me, thanks.
